import consoleCredits from "@/lib/generated/console-credits.json";
import type { CreditEntry } from "@/lib/firmware";

// Credits page content (docs/specs/finished/credits.md §2.2).

// GitHub Sponsors page, linked from the footer and Credits. Always a plain link out, never an
// in-app payment: donations keep the Vercel Hobby plan non-commercial.
export const SPONSOR_URL = "https://github.com/sponsors/tineira";

export type Thanks ={ name: string; role: string; url: string };

export const THANKS: Thanks[] = [
  { name: "Vercel", role: "Hosting and deploys for the console.", url: "https://vercel.com" },
  {
    name: "Neon",
    role: "Serverless Postgres for switches, recipes and firmware releases.",
    url: "https://neon.com",
  },
  {
    name: "Seeed Studio",
    role: "XIAO ESP32-S3 and ESP32-C6 boards, and the Round Display.",
    url: "https://www.seeedstudio.com",
  },
  {
    name: "Espressif",
    role: "ESP32 chips, ESP-IDF, and esptool-js, which flashes boards from the browser.",
    url: "https://www.espressif.com",
  },
];

// Generated by scripts/credits.mjs from package.json.
export const CONSOLE_CREDITS: CreditEntry[] = consoleCredits;
