// Writes lib/generated/schema.ts from db/schema.sql (docs/specs/schema-version.md §2.2).
// Runs as part of `prebuild`; rerun by hand (`npm run schema`) after editing db/schema.sql.
// `--check` exits 1 when the committed file is stale (CI).
import { readFileSync, writeFileSync } from "node:fs";
import { readSchema } from "./schema-sql.mjs";

const out = new URL("../lib/generated/schema.ts", import.meta.url);
const { statements, version } = readSchema();

const text = `// Generated by scripts/gen-schema.mjs from db/schema.sql. Do not edit; edit db/schema.sql.

export const SCHEMA_VERSION = ${JSON.stringify(version)};

export const SCHEMA_STATEMENTS: string[] = ${JSON.stringify(statements, null, 2)};
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== text) {
    console.error("lib/generated/schema.ts is stale: run `npm run schema` and commit it.");
    process.exit(1);
  }
  console.log(`lib/generated/schema.ts is current (${statements.length} statements, ${version})`);
} else {
  writeFileSync(out, text);
  console.log(`lib/generated/schema.ts: ${statements.length} statements, version ${version}`);
}
